// Mock API for Storybook
export const mockApi = {
  getPersonalizationScore: () => Promise.resolve([{ score: "85", changeScore: "5" }]),
  getNewEngagements: () => Promise.resolve([{ engagements: 120, changePercentage: 0.16 }]),
  getEngagementRate: () => Promise.resolve([{ engagementRate: 75, changePercentage: 0.05 }]),
  getRevenue: () => Promise.resolve([{ revenue: 150000, changePercentage: 0.10 }]),
  getTopics: () => Promise.resolve({
    totalItems: 2,
    currentOffset: 0,
    content: [
      {
        id: "101",
        value: "Celebrity news",
        contactIncidence: 369,
        topicIncidence: 2,
        coverageScore: 75,
        topicCompetition: "Low",
      },
      {
        id: "102",
        value: "Technology trends",
        contactIncidence: 245,
        topicIncidence: 5,
        coverageScore: 60,
        topicCompetition: "Medium",
      },
    ],
  }),
  getContacts: () => Promise.resolve({
    totalItems: 3,
    currentOffset: 0,
    content: [
      {
        id: "201",
        firstName: "Alice",
        lastName: "Johnson",
        email: "alice@amazon.com",
        company: "Amazon",
        insights: 45,
        recommendations: 12,
        industry: "Tech",
        jobTitle: "CTO",
        stage: "LEAD",
      },
      {
        id: "202",
        firstName: "Bob",
        lastName: "Smith",
        email: "bob@microsoft.com",
        company: "Microsoft",
        insights: 32,
        recommendations: 8,
        industry: "Tech",
        jobTitle: "VP Engineering",
        stage: "PROSPECT",
      },
      {
        id: "203",
        firstName: "Carol",
        lastName: "Davis",
        email: "carol@google.com",
        company: "Google",
        insights: 28,
        recommendations: 15,
        industry: "Tech",
        jobTitle: "Director of Product",
        stage: "CUSTOMER",
      },
    ],
  }),
  getCompetitors: () => Promise.resolve([
    {
      id: "301",
      name: "Competitor A",
      url: "https://competitor-a.com",
      score: 80,
      topics: ["AI", "Machine Learning"],
    },
    {
      id: "302",
      name: "Competitor B",
      url: "https://competitor-b.com",
      score: 65,
      topics: ["Data Science", "Analytics"],
    },
  ]),
  updateCompetitor: () => Promise.resolve(),
  addCompetitor: () => Promise.resolve(),
};
